### ISSUE TITLE
Update hello world manifest 

### ISSUE THREAD

**Issue by veratek** [massalabs/thyra-plugin-hello-world#24]
Update manifest with correct name and create description 

Expected: 
{
    "author" : "Massa Labs",
    "name" : "Hello World",
    "description" : "Hello world plugin to learn by doing",
    "logo" : "hello_world.svg",
    "home" : "",
    "version" : "0.0.6",
    "apispec":""
}

**Comment by veratek** [comment]
@SlnPons a official description is needed

**Comment by SlnPons** [comment]
Additional questions: 
- What's the current logo?
- How does the version is updated?

**Comment by veratek** [comment]
logo is : 
![Screenshot from 2023-06-21 15-02-28](https://github.com/massalabs/station-massa-hello-world/assets/90157528/55c84b19-1c07-4142-9c16-d7f2d997e143)
located [here](https://github.com/massalabs/station-massa-hello-world/blob/main/web/content/hello_world.svg)

**Comment by veratek** [comment]
the version is manually updated

**Comment by veratek** [comment]
No tests are ran in this manifest.json

**Comment by SlnPons** [comment]
Let's keep this one ;) 
Make sure it's 40x40px
